//Get All Users Of Specific Company
export const GET_COMPANY_USERS_REQ = "GET_COMPANY_USERS_REQ";
export const GET_COMPANY_USERS_SUCCESS = "GET_COMPANY_USERS_SUCCESS";
export const GET_COMPANY_USERS_FAIL = "GET_COMPANY_USERS_FAIL";

// Creating New User
export const CREATE_COMPANY_NEW_USER_REQ = "CREATE_COMPANY_NEW_USER_REQ";
export const CREATE_COMPANY_NEW_USER_SUCCESS =
  "CREATE_COMPANY_NEW_USER_SUCCESS";
export const CREATE_COMPANY_NEW_USER_FAIL = "CREATE_COMPANY_NEW_USER_FAIL";

//Delete User
export const DELETE_USER_REQ = "DELETE_USER_REQ";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

//Get User Data
export const GET_USER_DATA_BY_ID_REQ = "GET_USER_DATA_BY_ID_REQ";
export const GET_USER_DATA_BY_ID_SUCCESS = "GET_USER_DATA_BY_ID_SUCCESS";
export const GET_USER_DATA_BY_ID_FAIL = "GET_USER_DATA_BY_ID_FAIL";
