//All Users Of Specific Company

export const GET_COMPANY_USERS_REQ = "GET_COMPANY_USERS_REQ";
export const GET_COMPANY_USERS_SUCCESS = "GET_COMPANY_USERS_SUCCESS";
export const GET_COMPANY_USERS_FAIL = "GET_COMPANY_USERS_FAIL";
