//GetCompanies
export const GET_COMPANIES_REQ = "GET_COMPANIES_REQ";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

//GetCompanie Data
export const GET_COMPANIE_DATA_REQ = "GET_COMPANIE_DATA_REQ";
export const GET_COMPANIE_DATA_SUCCESS = "GET_COMPANIE_DATA_SUCCESS";
export const GET_COMPANIE_DATA_FAIL = "GET_COMPANIE_DATA_FAIL";

//Update Company
export const UPDATE_COMPANY_REQ = "UPDATE_COMPANY_REQ";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";
