//GetCompanies
export const GET_COMPANIES_REQ = "GET_COMPANIES_REQ";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

//GetCompanie Data
export const GET_COMPANIEDATA_REQ = "GET_COMPANIEDATA_REQ";
export const GET_COMPANIEDATA_SUCCESS = "GET_COMPANIEDATA_SUCCESS";
export const GET_COMPANIEDATA_FAIL = "GET_COMPANIEDATA_FAIL";
