//Get Companies of specific user
export const GET_COMPANIES_REQ = "GET_COMPANIES_REQ";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

//GetCompany Data
export const GET_COMPANIE_DATA_REQ = "GET_COMPANIE_DATA_REQ";
export const GET_COMPANIE_DATA_SUCCESS = "GET_COMPANIE_DATA_SUCCESS";
export const GET_COMPANIE_DATA_FAIL = "GET_COMPANIE_DATA_FAIL";

//Update Company
export const UPDATE_COMPANY_REQ = "UPDATE_COMPANY_REQ";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";

//GetCompany Data
export const DELETE_COMPANY_REQ = "DELETE_COMPANY_REQ";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";

//Get All Companies
export const GET_ALL_COMPANIES_REQ = "GET_ALL_COMPANIES_REQ";
export const GET_ALL_COMPANIES_SUCCESS = "GET_ALL_COMPANIES_SUCCESS";
export const GET_ALL_COMPANIES_FAIL = "GET_ALL_COMPANIES_FAIL";

//Create New Company
export const CREATE_NEW_COMPANY_REQ = "CREATE_NEW_COMPANY_REQ";
export const CREATE_NEW_COMPANY_SUCCESS = "CREATE_NEW_COMPANY_SUCCESS";
export const CREATE_NEW_COMPANY_FAIL = "CREATE_NEW_COMPANY_FAIL";
